name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - if: >
          !startsWith(github.head_ref, 'renovate/') &&
          !startsWith(github.head_ref, 'release-please--')
        run: We run
